apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: react-app
type: Opaque
data:
  VITE_SUPABASE_PROJECT_ID: cm5haWticHpsY3RlYnlwd2p2bnI=
  VITE_SUPABASE_PUBLISHABLE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5KdVlXbHJZbkI2YkdOMFpXSjVjSGRxZG01eUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTmprNE5EazJORFlzSW1WNGNDSTZNakE0TlRReU5UWTBObjAuOTR3LWxlNFhNejZLU0JWWWIyQzBtcmhUZmhtU0k1bm81SXdiZ3NralU1OA==
  VITE_SUPABASE_URL: aHR0cHM6Ly9ybmFpa2JwemxjdGVieXB3anZuci5zdXBhYmFzZS5jbw==